const LANGUAGE = 'LANGUAGE';
const COORD = 'COORD';
const AUTH = 'AUTH';
const USER_ID = 'USER_ID';
const POST_COORD = 'POST_COORD';
const FILTER = 'FILTER';

export  {LANGUAGE, COORD, AUTH, USER_ID, POST_COORD, FILTER}